name: CallChatGPT_build_main

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.OpenAI.CallChatGPT/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.OpenAI.CallChatGPT
      env_var_name_1: OPENAI_API_KEY
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.OPENAI_API_KEY }}
